WIP: Add pFUnit library for unit testing

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,6 +4,9 @@
 # The local build configuration is stored in make.vars,
 # which is NOT under version control.
 
+# Exit script immediately upon error
+set -euo pipefail
+
 # Output file name (do not change)
 VARS=make.vars
 
@@ -12,7 +15,13 @@ MPI=FALSE
 CP2K=FALSE
 PLUMED=FALSE
 FFTW=FALSE
+PFUNIT=FALSE
 ABINEXE=abin
+
+MPI_PATH=''
+PFUNIT_PATH=''
+PLUMED_PATH=''
+CP2K_PATH=''
 
 function show_help()
 {
@@ -21,7 +30,7 @@ NAME
    configure - generate local configuration for ABIN
 
 SYNOPSIS
-   configure [--debug] [--mpi path/to/mpi] [--plumed path/to/plumed] [--cp2k]
+   configure [--debug] [--mpi path/to/mpi] [--plumed path/to/plumed] [--pfunit path/to/pfunit] [--cp2k]
 
 OPTIONS
    --debug       Compile in debug mode
@@ -30,6 +39,8 @@ OPTIONS
    --plumed      Compile with Plumed library
    --fftw        Use FFTW library (needed for normal mode PIMD)
    --cp2k        Cross-compile with CP2K (experimental)
+   --pfunit      Compile with unit tests using pFUnit library
+                 (use ./install_pfunit.sh to install it first)
 "
 }
 
@@ -59,6 +70,15 @@ while [[ $# -gt 0 ]]; do
         PLUMED_PATH=$2
         shift 2
         ;;
+      --pfunit)
+        PFUNIT=TRUE
+        if [[ $# -lt 2 ]]; then
+            echo "Error: missing PFUNIT_PATH argument"
+            exit 1
+        fi
+        PFUNIT_PATH=$2
+        shift 2
+        ;;
       --fftw)
         echo "Using FFTW library, assuming it's in your LD_LIBRARY_PATH"
         FFTW=TRUE
@@ -75,19 +95,11 @@ while [[ $# -gt 0 ]]; do
     esac
 done
 
-echo "Generating local build configuration for ABIN"
-echo "Writing config to $VARS"
-echo "# Local build configuration" > $VARS
-echo "# This file was built as follows." >> $VARS
-echo "# $0 $PARAMS" >> $VARS
+# Set to default if FFLAGS is not defined yet, see
+# https://stackoverflow.com/questions/11362250/in-bash-how-do-i-test-if-a-variable-is-defined-in-u-mode
+: ${FFLAGS:='-O2 -fopenmp'}
 
-if [[ -z $FFLAGS ]];then
-   # Default build
-   # Overwrite this by exporting FFLAGS before running configure
-   FFLAGS="-O2 -fopenmp"
-fi
-
-if [[ -z $FC ]];then
+if [[ -z ${FC-} ]];then
    if [[ $MPI = "TRUE" ]];then
       if [[ $MPI_PATH != "" ]];then
          FC=$MPI_PATH/bin/mpifort
@@ -102,7 +114,8 @@ if [[ -z $FC ]];then
 fi
 
 if [[ ! -f $FC && ! `which $FC` ]];then
-   echo "ERROR: $FC not found"
+   echo "ERROR: program \"$FC\" not found"
+   echo "Consider exporting variable \"FC\" manually"
    exit 1
 fi
 
@@ -123,9 +136,15 @@ if [[ $PLUMED = "TRUE" ]];then
    fi
 fi
 
+echo "Generating local build configuration for ABIN"
+echo "Writing config to $VARS"
+
 # Print all vars to make.vars
 echo "
-# This file is included in Makefile
+# Local build configuration, this file is included into Makefile
+
+# This file was built as follows.
+# $0 $PARAMS
 
 # Name of the final binary
 BIN = $ABINEXE
@@ -160,6 +179,10 @@ FFTW = $FFTW
 
 # Experimental cross-compilation with CP2K
 CP2K = $CP2K
+
+# Compile with unit tests
+PFUNIT = $PFUNIT
+PFUNIT_PATH = $PFUNIT_PATH
 " >> make.vars
 
 # TODO: Make automatic check for FFTW library
@@ -168,7 +191,7 @@ if [[ $CP2K = "TRUE" ]];then
    echo "Linkink with CP2K"
    echo "Setup paths to CP2K libs manually in make.vars"
    echo "
-CP2KPATH = /usr/local/src/programes/src/cp2k-2.6.2/lib/Linux-x86-64-gfortran-mkl/sopt/
+CP2K_PATH = /usr/local/src/programes/src/cp2k-2.6.2/lib/Linux-x86-64-gfortran-mkl/sopt/
 MKL = /intel/parallel_studio_2015_update5/mkl/lib/intel64/
 LIBINT_LIB = /libint/1.1.4-gcc/lib
 FFTW_LIB = /fftw/3.3.4-gcc/lib/
